Days: 31
MandatoryWorld: W_DonationBoard
PerkClaimAfterSeconds: 10
PerkLevelGroups: [PerkLevel1, PerkLevel2, PerkLevel3, PerkLevel4, PerkLevel5]

eithon:
  UseMarkUpForMessages: 1
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 2

commands:
  #
  # Parameters: <player>(%s) <perk level>(%d)
  AddGroupCommand: perm player %s addgroup PerkLevel%d

  #
  # Parameters: <player>(%s) <perk level>(%d)
  RemoveGroupCommand: perm player %s removegroup PerkLevel%d
  
  #
  # Parameters: -
  NoTokensLeft: You have no E-tokens left.

  #
  # Parameters: <remaining tokens> (%d)
  TokensLeft: You have %d remaining E-tokens.

messages:
  #
  # No parameters
  NeedTokens: You must have E-tokens to raise the perk level.

  #
  # No parameters
  HowToGetTokens: You get E-tokens by donating at http://eithon.net/shop.

  #
  # Parameters: <player name> (%s)
  PlayerHasDonated: Player %s has made a donation for today!

  #
  # Parameters: -
  NoTokensLeft: You have no E-tokens left.

  #
  # Parameters: <remaining tokens> (%d)
  TokensLeft: You have %d remaining E-tokens.

  #
  # Parameters: <new perk level> (%d)
  VisitBoard: If you visit the donation board, you can raise your perk level to %d.

  #
  # Parameters: <current perk level> (%d)
  NoChangeInPerkLevel: You have the correct perk level (%d).

  #
  # Parameters: <new perk level> (%d)
  PerkLevelChanged: "[title/][color=aqua]Perk Level %d[/color][subtitle/][color=darkaqua]You were added to Today's Perk Level![/color][actionbar/]Today's Sponsors; Not yet added!"